# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

[nodejs]
symbol = 'ğŸ“¦ '
detect_files = ['package.json']

[terraform]
detect_files = ['*.tf', '*.tfvars']

[git_branch]
symbol = 'ğŸŒ± '
format = 'on [$symbol$branch(:$remote_branch)]($style) '

[git_state]
format = '([\[$all_status\] \[$ahead_behind$count\] ( $progress_current of $progress_total)]($style) )'
cherry_pick = '[ğŸ’ PICKING](bold red)'

[aws]
disabled = true

[gcloud]
disabled = true

[hostname]
ssh_only = false
format = "[cloudshell](bold yellow) "
